apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: tester
  labels:
    app: tester
    copyMe: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
    spec:
      containers:
      - name: tester
        image: ubuntu
        command:
          - "sleep"
          - "infinity"
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
---
apiVersion: cache.mezmo.com/v1alpha1
kind: Copy
metadata:
  labels:
    app.kubernetes.io/name: copy
    app.kubernetes.io/instance: copy-sample
    app.kubernetes.io/part-of: copy-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: copy-operator
  name: copy-sample
spec:
  sourceNamespace: test